### ISSUE TITLE
Xcode 14 Thread Performance Checker warning

### ISSUE THREAD

**Issue by PGHM** [KatalysatorAB/glimr-sdk-swift#1]
[Xcode 14](https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes) has a new debug feature called Thread Performance Checker. With this checker on, I get a warning:

This method can cause UI unresponsiveness if invoked on the main thread. Instead, consider waiting for the -locationManagerDidChangeAuthorization: callback and checking authorizationStatus first.

It is originated from GLLocationManager calling locationServiceEnabled.

![Screenshot 2022-09-29 at 12 11 16](https://user-images.githubusercontent.com/2285298/192991437-3b19d9b6-2c82-4dc5-8fa5-180413c79749.png)

**Comment by svenroed** [comment]
resolved with https://github.com/KatalysatorAB/glimr-sdk-swift/commit/a4c24d2e7fb0ca2ff817115f9024bbc9e25c867c
